name: Generate Rust Bindings

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-bindings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-14 llvm-14-dev lld-14
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 100
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 100
          sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-14 100

      - name: Set Environment Variables
        run: |
          echo "CC=clang-14" >> $GITHUB_ENV
          echo "CXX=clang++-14" >> $GITHUB_ENV
          echo "RUSTFLAGS=-C linker=clang-14 -C link-arg=-fuse-ld=lld-14" >> $GITHUB_ENV

      - name: Build the Project
        run: cargo build

      - name: Commit Generated Bindings
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/bindings/bindings.rs
          git commit -m "Automatically generated Rust bindings"
          git push
